name: ParaCL post-push
on:
  push:
      paths:
        - ParaCL/**
      branches:
        - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Compiler dependency
      run: sudo apt-get install g++
    - name: Boost dependency
      run: sudo apt-get install libboost-all-dev
    - name: GTest dependency
      run: sudo apt install libgtest-dev
    - name: Flex dependency
      run: sudo apt-get install flex && sudo apt-get install libfl-dev
    - name: Bison dependency
      run: sudo apt-get install bison
    - name: CMake configure
      run: cmake -S ParaCL/ -B ParaCL/build -DCMAKE_CXX_COMPILER=g++
    - name: CMake build
      run: cmake --build ParaCL/build
    - name: Run tests
      run: ./ParaCL/build/paracl_test && ./ParaCL/build/vm_test
